### ISSUE TITLE
AttributeError: module 'matplotlib' has no attribute 'colormaps'

### ISSUE THREAD

**Issue by santiagolopezg** [moshi4/pyCirclize#22]
Running into this issue after installing ``pycirclize`` via Anaconda (``conda install -c conda-forge pycirclize``), and attempting to run ``from pycirclize import Circos``. 
My specs:
* python 3.8.16;
* pycirclize 0.3.1 from conda-forge;
* matplotlib 3.1.3

![error](https://user-images.githubusercontent.com/17716632/236352096-7dc1b72b-b627-44a6-a0b9-df9c184a7012.png)

**Comment by moshi4** [comment]
The installation of pyCirclize requires `matplotlib>=3.5.2`.
However, your environment has `matplotlib==3.1.3`, which does not satisfy the package dependency of pyCirclize.

Please update matplotlib or try reinstalling pycirclize in the new conda virtual environment.
