### ISSUE TITLE
Preserve order of tsv rows during rendering

### ISSUE THREAD

**Issue by naturepoker** [moshi4/pyCirclize#28]
Hi, 

Thanks for the wonderful package - I've been having a lot of fun with it. 

I'm trying to produce a linked circle plot with an imported tsv file (three column consisting of from/too/value) - everything seems to work okay, except rendered image re-orders the first column into alphabetical order. 
Is there a way to suppress that behavior and preserve the order in the input tsv file? 

Attaching current code for reference:

```python
from pycirclize import Circos
from pycirclize.parser import Matrix
import pandas as pd

fromto_table_df = pd.read_csv("sorted.tsv",sep="\t")

matrix = Matrix.parse_fromto_table(fromto_table_df)

circos = Circos.initialize_from_matrix(
	matrix,
	space=1,
	cmap="tab10",
	label_kws=dict(size=3, orientation="vertical"),
	link_kws=dict(ec="white", lw=0),
)

fig = circos.savefig('sorted.png', dpi=500)
```

Thank you!

**Comment by moshi4** [comment]
Hi @naturepoker,

pyCirclize does not provide a way to preserve the row order when converting from a tsv file to a matrix.
However, users can freely change the node order in Chord Diagram by using the `order` option of [Circos.initialize_from_matrix()](https://moshi4.github.io/pyCirclize/api-docs/circos/#pycirclize.circos.Circos.initialize_from_matrix).

The following is an example code using the `order` option.

```python
from pycirclize import Circos
from pycirclize.parser import Matrix
import pandas as pd

fromto_table_df = pd.DataFrame(
    [
        ["A", "B", 10],
        ["A", "C", 5],
        ["A", "D", 15],
        ["A", "E", 20],
        ["A", "F", 3],
        ["B", "A", 3],
        ["B", "G", 15],
        ["F", "D", 13],
        ["F", "E", 2],
        ["E", "A", 20],
        ["E", "D", 6],
    ],
    columns=["from", "to", "value"],
)
matrix = Matrix.parse_fromto_table(fromto_table_df)

circos = Circos.initialize_from_matrix(
    matrix,
    space=3,
    order=["C", "D", "E", "F", "B", "A", "G"], # Set user-defined order
    label_kws=dict(size=12, r=105),
    link_kws=dict(direction=1, ec="black", lw=0.5),
)

circos.savefig("result.png")
```

![result](https://github.com/moshi4/pyCirclize/assets/41852815/ee82703c-b5e8-44a7-b5e8-08befd1843bd)

**Comment by naturepoker** [comment]
This worked perfectly, thank you!
