### ISSUE TITLE
DIC object Not callable 

### ISSUE THREAD

**Issue by DEV-SRB** [moshi4/pyCirclize#39]
while defining the new dictionary  for c map in below code, the error can be seen in label_kws and link_kws 
color_dict = {}

    for i in np.array(rows_df['Rows']):
        color_dict[i] = "blue"
    for i in np.array(cols_df['Columns']):
        color_dict[i] = "red"

    circos = Circos.initialize_from_matrix(
        matrix_df,
        space=2,
        cmap='tab10',  # Use color_dict as the colormap
        label_kws = dict(size=8, orientation='vertical'),
        link_kws=dict(ec='black', lw=0.5, direction=1, hatch="//"),
    )

**Comment by moshi4** [comment]
The partial error output and code shown does not help me determine the cause of the error.

Could you please provide example code and data so that I can reproduce this error?
___

You may have misunderstood how to use **cmap dictionary** in `Circos.initialize_from_matrix()`, so here is a code example.

```python
from pycirclize import Circos
import pandas as pd

# Create matrix dataframe (3 x 6)
row_names = ["S1", "S2", "S3"]
col_names = ["E1", "E2", "E3", "E4", "E5", "E6"]
matrix_data = [
    [4, 14, 13, 17, 5, 2],
    [7, 1, 6, 8, 12, 15],
    [9, 10, 3, 16, 11, 18],
]
matrix_df = pd.DataFrame(matrix_data, index=row_names, columns=col_names)

# Initialize from matrix (Can also directly load tsv matrix file)
circos = Circos.initialize_from_matrix(
    matrix_df,
    space=5,
    r_lim=(93, 100),
    # cmap="tab10",
    cmap=dict(S1="red", S2="blue", S3="green", E1="grey", E2="grey", E3="grey", E4="grey", E5="grey", E6="grey"),
    label_kws=dict(r=94, size=12, color="white"),
    link_kws=dict(ec="black", lw=0.5),
)
circos.savefig("result.png")
```

**result.png**

![result](https://github.com/moshi4/pyCirclize/assets/41852815/705bbdf9-5f72-4e55-a7dd-fd1a5f1b4bdc)

**Comment by DEV-SRB** [comment]
Actually I am plotting the chord-diagram for the data in an excel file, so am trying to keep one color for the row values and another color for the column values but i am facing the above issue while passing the color through dictionary to cmap.




import pandas as pd  
import numpy as np  
from pycirclize import Circos  

def filter_data_and_create_matrix(fname, col1, col2, filter_col, threshold):
    file_path = fname
    df = pd.read_excel(file_path)

    #  Filtering based on the specified threshold
    df = df[df[filter_col] > threshold]

    # Extracting unique values from the specified columns
    column1_values = df[col1].unique()
    column2_values = df[col2].str.split(',').explode().str.strip().unique()

    # Zero Matrix
    matrix = np.zeros((len(column1_values), len(column2_values)))

    # Matrix based on column values & filtering criteria
    for i, value1 in enumerate(column1_values):
        for j, value2 in enumerate(column2_values):
            if any((df[col1] == value1) & (df[col2].str.contains(value2))):
                matrix[i][j] = 1

    # DataFrames for rows and columns
    rows_df = pd.DataFrame(column1_values, columns=['Rows'])
    cols_df = pd.DataFrame(column2_values, columns=['Columns'])

    # DataFrame for the matrix
    matrix_df = pd.DataFrame(matrix, columns=cols_df['Columns'], index=rows_df['Rows'])

    return matrix_df

# Function to create Circos plot from a matrix and save it as an SVG file
def create_circos_plot(matrix_df, space_size, svg_file_name):
    circos = Circos.initialize_from_matrix(
        matrix_df,
        space=space_size,
        cmap="tab10",
        label_kws=dict(size=8, orientation='vertical'),
        link_kws=dict(ec="black", lw=0.5, direction=1, hatch="//"),
    )
 
    circos.savefig(svg_file_name)


# Specify the input file name, columns, and filtering criteria
# filtered_matrix_df = filter_data_and_create_matrix('FILE_NAME.xlsx', 'COL_1', 'COL_2', 'CUT_OFF_COL', CUT_OFF_SIZE)

filtered_matrix_df = filter_data_and_create_matrix('Gene.xlsx', 'term_id', 'intersections', 'intersection_size', 2)

# Create a Circos plot from the filtered matrix and save it as 'example04.svg'
# create_circos_plot(filtered_matrix_df, SPACE_SIZE_B/W_SEC, 'IMAGE_FILE_NAME.svg')

create_circos_plot(filtered_matrix_df, 2, 'example04.svg')

**Comment by DEV-SRB** [comment]
Thank you For your Response, Is it possible to give different colors to labels?

**Comment by moshi4** [comment]
I can't reproduce the error without the data file.

Could you also upload `Gene.xlsx`? If it is not possible to upload the research data as is, dummy data with appropriate numerical changes is fine.

**Comment by DEV-SRB** [comment]
I apologize for the confusion, but i solved the error thanks to your example, but I wanted to change the label colors to differentiate between row and column values. I am sharing my example data and  the code here below. And I appreciate your quick responses to my queries.

Here below is my code,

`
import pandas as pd  
import numpy as np  
from pycirclize import Circos  

color_dict={}
def filter_data_and_create_matrix(fname, col1, col2, filter_col, threshold):
    file_path = fname
    df = pd.read_excel(file_path)

    #  Filtering based on the specified threshold
    df = df[df[filter_col] > threshold]

    # Extracting unique values from the specified columns
    column1_values = df[col1].unique()
    column2_values = df[col2].str.split(',').explode().str.strip().unique()

    # Zero Matrix
    matrix = np.zeros((len(column1_values), len(column2_values)))

    # Matrix based on column values & filtering criteria
    for i, value1 in enumerate(column1_values):
        for j, value2 in enumerate(column2_values):
            if any((df[col1] == value1) & (df[col2].str.contains(value2))):
                matrix[i][j] = 1

    # DataFrames for rows and columns
    rows_df = pd.DataFrame(column1_values, columns=['Rows'])
    cols_df = pd.DataFrame(column2_values, columns=['Columns'])

    # DataFrame for the matrix
    matrix_df = pd.DataFrame(matrix, columns=cols_df['Columns'], index=rows_df['Rows'])
    # for i in np.array(rows_df['Rows']):
    #     color_dict[i] = "blue"
    # for i in np.array(cols_df['Columns']):
    #     color_dict[i] = "red"
    return matrix_df
#ciros plot 
def create_circos_plot(matrix_df, space_size, svg_file_name):
    circos = Circos.initialize_from_matrix(
        matrix_df,
        space=space_size,
        cmap='tab10', #Can use dic 'color_dict'
        label_kws=dict(size=8, orientation='vertical'),
        link_kws=dict(ec="black", lw=0.5, direction=1, hatch="//"),
    )
    circos.savefig(svg_file_name)
    
filtered_matrix_df = filter_data_and_create_matrix('Gene.xlsx', 'term_id', 'intersections', 'intersection_size', 2)
create_circos_plot(filtered_matrix_df, 2, 'example04.svg')

`
[Gene.xlsx](https://github.com/moshi4/pyCirclize/files/12547607/Gene.xlsx)

**Comment by moshi4** [comment]
It is possible to change the label color as shown in the code example below.

```python
from pycirclize import Circos
import pandas as pd

# Create matrix dataframe (3 x 6)
row_names = ["S1", "S2", "S3"]
col_names = ["E1", "E2", "E3", "E4", "E5", "E6"]
matrix_data = [
    [4, 14, 13, 17, 5, 2],
    [7, 1, 6, 8, 12, 15],
    [9, 10, 3, 16, 11, 18],
]
matrix_df = pd.DataFrame(matrix_data, index=row_names, columns=col_names)

# Initialize from matrix (Can also directly load tsv matrix file)
cmap = dict(S1="red", S2="blue", S3="green", E1="grey", E2="grey", E3="grey", E4="grey", E5="grey", E6="grey")
circos = Circos.initialize_from_matrix(
    matrix_df,
    space=5,
    r_lim=(93, 100),
    cmap=cmap,
    label_kws=dict(size=0, color="none"), # Disable plotting label automatically
    link_kws=dict(ec="black", lw=0.5),
)
# Manually plot label
for sector in circos.sectors:
    label_color = cmap[sector.name]
    sector.text(sector.name, r=105, color=label_color, size=12)

circos.savefig("result.png")
```

**result.png**

![result](https://github.com/moshi4/pyCirclize/assets/41852815/00036170-35ea-46d9-b1e4-e8452d59100d)

**Comment by DEV-SRB** [comment]
Thank you
