### ISSUE TITLE
Is there a way to plot shapes on tracks?

### ISSUE THREAD

**Issue by dongzhang0725** [moshi4/pyCirclize#48]
Can we plot shapes of matplotlib (https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers) on a track of the tree figure? If so, can anyone give me an example? Thank you!
For example:
![image](https://github.com/moshi4/pyCirclize/assets/15956921/7d464cbc-6d86-4e96-9826-4fb9a16ae3e7)

**Comment by moshi4** [comment]
Hi @dongzhang0725,

I think `track.scatter()` method can do roughly the same thing.

**Code Example**

```python
from pycirclize import Circos
from pycirclize.utils import load_example_tree_file, ColorCycler
import random

tree_file = load_example_tree_file("large_example.nwk")
circos, tv = Circos.initialize_from_tree(
    tree_file,
    r_lim=(40, 90),
    leaf_label_size=5,
    leaf_label_rmargin=10,
    label_formatter=lambda t: t.replace("_", " "),
)

# Add track for marker plot
tree_sector = circos.sectors[0]
track = tree_sector.add_track((90, 100))

# Plot 3 layer markers for leaf labels
for leaf_label in tv.leaf_labels:
    x = tv.name2xr[leaf_label][0]
    track.scatter(x=[x], y=[0.2], vmin=0, vmax=1, color="salmon")
    track.scatter(x=[x], y=[0.5], vmin=0, vmax=1, color="skyblue", marker="s")
    if random.random() > 0.5:
        track.scatter(x=[x], y=[0.8], vmin=0, vmax=1, color=ColorCycler(), marker="*", s=25)

circos.savefig("example.png", dpi=300)
```

**example.png**

![example](https://github.com/moshi4/pyCirclize/assets/41852815/1558c832-167d-4ed7-981d-d6dc7bd29cdc)

**Comment by dongzhang0725** [comment]
> Hi @dongzhang0725,
> 
> I think `track.scatter()` method can do roughly the same thing.
> 
> **Code Example**
> 
> ```python
> from pycirclize import Circos
> from pycirclize.utils import load_example_tree_file, ColorCycler
> import random
> 
> tree_file = load_example_tree_file("large_example.nwk")
> circos, tv = Circos.initialize_from_tree(
>     tree_file,
>     r_lim=(40, 90),
>     leaf_label_size=5,
>     leaf_label_rmargin=10,
>     label_formatter=lambda t: t.replace("_", " "),
> )
> 
> # Add track for marker plot
> tree_sector = circos.sectors[0]
> track = tree_sector.add_track((90, 100))
> 
> # Plot 3 layer markers for leaf labels
> for leaf_label in tv.leaf_labels:
>     x = tv.name2xr[leaf_label][0]
>     track.scatter(x=[x], y=[0.2], vmin=0, vmax=1, color="salmon")
>     track.scatter(x=[x], y=[0.5], vmin=0, vmax=1, color="skyblue", marker="s")
>     if random.random() > 0.5:
>         track.scatter(x=[x], y=[0.8], vmin=0, vmax=1, color=ColorCycler(), marker="*", s=25)
> 
> circos.savefig("example.png", dpi=300)
> ```
> 
> **example.png**
> 
> ![example](https://private-user-images.githubusercontent.com/41852815/294808658-1558c832-167d-4ed7-981d-d6dc7bd29cdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODY0NzMsIm5iZiI6MTcwNDY4NjE3MywicGF0aCI6Ii80MTg1MjgxNS8yOTQ4MDg2NTgtMTU1OGM4MzItMTY3ZC00ZWQ3LTk4MWQtZDZkYzdiZDI5Y2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAzNTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZjc5MGNmNTI4OGFkNWRlN2UzNjQwYjI3NzA2YWFmMDE2OGE1Yjk2YmVkM2EwNTQwZDE2ZmU2YjgwYzQxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4s5w4270fm4dBnvIJciYMyRz5yPIZcHUCxykuDpdFJM)

Dear @moshi4 ,

Thank you for your prompt response; it works like a charm. Pycirclize proves to be very powerful and convenient. I am planning to utilize it for tree annotations. I have an additional question regarding the display of support values on the nodes, as this is crucial for phylogenetic tree visualization, and I did not find relevant information on the homepage. Specifically, I am interested in displaying support value text on the branches of MCA, similar to this example:
![image](https://github.com/moshi4/pyCirclize/assets/15956921/b5480cad-432d-4975-b342-9d771c1376a4)

On another note, is there a way to convert the circular tree to a rectangular mode? If so, I believe it could be a promising tool to replace iTOL, an online tree annotation tool that requires a subscription.

**Comment by moshi4** [comment]
> I have an additional question regarding the display of support values on the nodes, as this is crucial for phylogenetic tree visualization, and I did not find relevant information on the homepage. Specifically, I am interested in displaying support value text on the branches of MCA

**Example Code**

Plot bootstrap values on each internal node in tree.

```python
from pycirclize import Circos
from pycirclize.utils import load_example_tree_file
import random

tree_file = load_example_tree_file("large_example.nwk")
circos, tv = Circos.initialize_from_tree(
    tree_file,
    r_lim=(20, 100),
    leaf_label_size=5,
    label_formatter=lambda t: t.replace("_", " "),
    line_kws=dict(color="grey"),
)

# Set tentative bootstrap value to internal nodes of tree
# 'large_example.nwk' has no bootstrap value
for innode in tv.tree.get_nonterminals():
    innode.confidence = random.randint(90, 100)

# Plot bootstrap value on each internal node in tree
sector = circos.sectors[0]
for innode in tv.tree.get_nonterminals():
    x, r =tv.name2xr[innode.name]
    if innode.confidence is not None:
        bootstrap_value = str(innode.confidence)
        sector.text(bootstrap_value, x, r + 0.5, size=5, color="black", orientation="vertical")

circos.savefig("example.png", dpi=300)
```

**example.png**

![example](https://github.com/moshi4/pyCirclize/assets/41852815/d19b8803-64ef-488b-8e64-fcbe34a6af88)

It may be good idea to add a method to the [TreeViz](https://moshi4.github.io/pyCirclize/api-docs/treeviz) class to more easily perform bootstrap value plots. I will consider this in the next release.

> On another note, is there a way to convert the circular tree to a rectangular mode? 

pyCirclize does not provide a way to convert a circular tree to a rectangular tree. Since pyCirclize is a "Circular visualization in Python" library, it is not intended to implement tree plotting in rectangular mode.
If you want to plot trees in rectangular mode as well as pyCirclize, you may be interested in looking at the [phyTreeViz](https://github.com/moshi4/phyTreeViz) library.

**Comment by dongzhang0725** [comment]
> > I have an additional question regarding the display of support values on the nodes, as this is crucial for phylogenetic tree visualization, and I did not find relevant information on the homepage. Specifically, I am interested in displaying support value text on the branches of MCA
> 
> **Example Code**
> 
> Plot bootstrap values on each internal node in tree.
> 
> ```python
> from pycirclize import Circos
> from pycirclize.utils import load_example_tree_file
> import random
> 
> tree_file = load_example_tree_file("large_example.nwk")
> circos, tv = Circos.initialize_from_tree(
>     tree_file,
>     r_lim=(20, 100),
>     leaf_label_size=5,
>     label_formatter=lambda t: t.replace("_", " "),
>     line_kws=dict(color="grey"),
> )
> 
> # Set tentative bootstrap value to internal nodes of tree
> # 'large_example.nwk' has no bootstrap value
> for innode in tv.tree.get_nonterminals():
>     innode.confidence = random.randint(90, 100)
> 
> # Plot bootstrap value on each internal node in tree
> sector = circos.sectors[0]
> for innode in tv.tree.get_nonterminals():
>     x, r =tv.name2xr[innode.name]
>     if innode.confidence is not None:
>         bootstrap_value = str(innode.confidence)
>         sector.text(bootstrap_value, x, r + 0.5, size=5, color="black", orientation="vertical")
> 
> circos.savefig("example.png", dpi=300)
> ```
> 
> **example.png**
> 
> ![example](https://private-user-images.githubusercontent.com/41852815/294827167-d19b8803-64ef-488b-8e64-fcbe34a6af88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTgyNjUsIm5iZiI6MTcwNDY5Nzk2NSwicGF0aCI6Ii80MTg1MjgxNS8yOTQ4MjcxNjctZDE5Yjg4MDMtNjRlZi00ODhiLThlNjQtZmNiZTM0YTZhZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ODFiYWQxODExYTFmOGQyNmM5MTRmN2I1MDYzM2UwYzM0YzUyMTEyYmIwZWI0M2MwMTRjZmNiMjQ3YWVjNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NcfApadgD_yko7X28J2mcToj05SZahG9VdXZP5SWMo4)
> 
> It may be good idea to add a method to the [TreeViz](https://moshi4.github.io/pyCirclize/api-docs/treeviz) class to more easily perform bootstrap value plots. I will consider this in the next release.
> 
> > On another note, is there a way to convert the circular tree to a rectangular mode?
> 
> pyCirclize does not provide a way to convert a circular tree to a rectangular tree. Since pyCirclize is a "Circular visualization in Python" library, it is not intended to implement tree plotting in rectangular mode. If you want to plot trees in rectangular mode as well as pyCirclize, you may be interested in looking at the [phyTreeViz](https://github.com/moshi4/phyTreeViz) library.

Dear @moshi4 ,

Thank you for providing the code; it has been very helpful.  I am also experimenting with integrating a text() function into the TreeViz class, which is derived from the marker() function, and I have achieved some initial success with it.
```
def text(
          self,
          query: str | list[str] | tuple[str],
          text,
          *,
          size: int = 6,
          **kwargs,
  ) -> None:
      target_node_name = self.search_target_node_name(query)

      # Set markers (x, r) coordinates (include descendent nodes)
      x: list[float] = []
      r: list[float] = []
      rmin, rmax = self.track.r_plot_lim
      clade: Clade = next(self.tree.find_clades(target_node_name))
      descendent_nodes: list[Clade] = list(clade.find_clades())
      for descendent_node in descendent_nodes:
          node_x, node_r = self.name2xr[str(descendent_node.name)]
          if descendent_node.is_terminal() and self._align_leaf_label:
              node_r = rmax if self._outer else rmin
          x.append(node_x)
          r.append(node_r)

      # If `descendent=False`, remove descendent nodes (x, r) coordinate
      # if not descendent:
      x, r = x[0], r[0]

      self.track.text(text, x, r, **kwargs)
```

If you are planning to add a method to draw text to the TreeViz class, I have an alternative suggestion concerning the text's position (which can also be applied to markers). Specifically, consider finding a way to obtain the position (x and r) of the center of the branch of MCA. This would allow the text to be positioned at the center of the internal branches. Following this, we may also need some adjustments to shift the x position and avoid overlaps between text and branches.

For example:
![image](https://github.com/moshi4/pyCirclize/assets/15956921/faf5574d-a04b-4c43-ac53-bdb2db23133f)

`If you want to plot trees in rectangular mode as well as pyCirclize, you may be interested in looking at the [phyTreeViz](https://github.com/moshi4/phyTreeViz) library.`
It's great to learn that you've developed a separate package for handling rectangular trees. I will explore the source code to attempt combining various plots (barplot, pieplot, scatter, etc.) with it.

Thank you for your helps again,

Dong

**Comment by moshi4** [comment]
I close this issue because the issue of the title has been resolved.

Other feature requests raised in the discussion will be considered separately.
