### ISSUE TITLE
Is there any way to integrate between heatmap data and tree leaves?

### ISSUE THREAD

**Issue by Zymeth0211** [moshi4/pyCirclize#50]
Dear Moshi04.

Thank you for your perfect system to create a beautiful combination of tree and heatmap.

I have a question about data integration between heatmap data and tree leaves. How do you integrate between them?

```
from pycirclize import Circos
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#Import the tree
tree_file = "\\tree_test\\abs alignment_tree.nwk"

# Sample DataFrame
df= pd.read_csv("\\tree_test\\abs_abundance.csv", index_col= 0)
print(df)

#make a tree with pycirclize
circos, tv = Circos.initialize

_from_tree(
    tree_file,
    start=5,
    end=355,
    leaf_label_size=8,
    align_leaf_label=True,
    ladderize=True,
    r_lim=(0, 60),
    leaf_label_rmargin=10,
    ignore_branch_length=True,
    )

#making heatmap
sector = circos.sectors[0]
track1 = sector.add_track((60, 65))
track1.heatmap(df["4R"], cmap="Reds", show_value=False)
track1.text("4R",adjust_rotation=False,color="black", r=20)

track2 = sector.add_track((65, 70))
track2.heatmap(df["3R"], cmap="Reds", show_value=False)
circos.colorbar(bounds=(1.0, 0.6, 0.02, 0.3),cmap="Reds", )
fig = circos.plotfig(), 
```
output 
![6d3fc1f1-21ff-49c5-af81-de31babf63ea](https://github.com/moshi4/pyCirclize/assets/155029380/801c8123-2d02-45e5-a155-3e39c23f1dfc)

Here is zip containing nwk and abundance data for heat map.

I apologize to ask you basic things.
[tree_test.zip](https://github.com/moshi4/pyCirclize/files/13957904/tree_test.zip)

Thank you
Best regards.

**Comment by moshi4** [comment]
I am not sure what "integrate" means. Could you please clarify what you mean?

**Comment by Zymeth0211** [comment]
Dear Moshi4

Thank you for your rapid response.

In my case, the tree data and heat map data frame are not correctly synchronized. For example, Cl_1995 has to be lighter in terms of color due to its small value.
