### ISSUE TITLE
How to use vmin argument in `track.line()` method

### ISSUE THREAD

**Issue by Thallam-Prashanth** [moshi4/pyCirclize#60]
Sir I am following this syntax to construct a line plot in pycircilize: 

track.line( x: list[float] | np.ndarray, y: list[float] | np.ndarray, *,vmin: float = 0, vmax: float | None = None, arc: bool = True, **kwargs).

I am just replacing vmin: float(np.min(y)) because line plot should not start with default zero. I am failing in providing vmin and it is showing syntax error. any suggestions sir.

**Comment by moshi4** [comment]
Your question lacks the information to answer it, so there is no way to answer it.
In asking your question, you should clarify what code you wrote and what error you encountered.
Also, the title "Doubt regarding circlize" is inappropriate, so you should title your question in such a way that it is clear what kind of question you are asking.

Finally, I will show you a simple code example using `track.line()` with vmin argument.

**Code Example**

```python
from pycirclize import Circos
import numpy as np

circos = Circos(sectors=dict(test=100), end=350)
sector = circos.sectors[0]

x = np.arange(0, 100)
y = np.random.randint(353, 356, len(x)) # Y value 353 - 355

# Plot y = (0 - 355) range
track1 = sector.add_track((80, 100), r_pad_ratio=0.1)
track1.axis()
track1.xticks_by_interval(5, outer=False)
track1.yticks([0, max(y)], [str(0), str(max(y))], side="left")
track1.line(x, y, color="red")

# Plot y = (353 - 355) range
track2 = sector.add_track((50, 70), r_pad_ratio=0.1)
track2.axis()
track2.xticks_by_interval(5, outer=False)
track2.yticks([min(y), max(y)], [str(min(y)), str(max(y))], vmin=min(y), side="left")
track2.line(x, y, vmin=min(y), color="blue")

circos.savefig("example.png")
```

**example.png**
![example](https://github.com/moshi4/pyCirclize/assets/41852815/64081976-6791-4aaf-afb8-8dff7dedf525)

I'm not going to teach you any more than that, so you'll have to do the rest on your own.
