### ISSUE TITLE
Question: Linear tree visualization

### ISSUE THREAD

**Issue by maxibor** [moshi4/pyCirclize#61]
Hey @moshi4 ,
Thanks for developping pyCirclize, it's really a very nice tool to visualize Phylogenetic trees and their associated metadata.
I have some trees that I would like to visualize using pyCirclize, but they have very few tips, and a linear visualization would probably be better than a circular one.

Is this something that is possible with pyCirclize ?

**Comment by moshi4** [comment]
Hi @maxibor,

pyCirclize does not provide the functionality to plot a linear phylogenetic tree. Also, I do not plan to add the functionality to plot linear phylogenetic trees, as it does not fit the concept of "Circular visualization in Python".

If you are interested in plotting linear phylogenetic trees, [phyTreeViz](https://github.com/moshi4/phyTreeViz) may be helpful. phyTreeViz is not as flexible as pyCirclize, but it does provide basic linear phylogenetic tree plotting functionality.

**Comment by maxibor** [comment]
Thanks for the quick answer @moshi4 ,
I was just wondering since AFAIK, pyCirclize is the most flexible solution for plotting phylogenetic trees with associated metadata (heatmap) in Python, and I saw a few mentions of a linear layout in your code https://github.com/moshi4/pyCirclize/blob/4a3c82a99df81e23708ffbd349abdad7ca0b0acb/src/pycirclize/circos.py#L596

Thanks for the clarification anyway !
