### ISSUE TITLE
Highlight different gene functioins with different tick/label colors and jitter labels

### ISSUE THREAD

**Issue by muntean-alex** [moshi4/pyCirclize#62]
First off, I'd like to thank you for providing such a great tool!
To the point to which I am writing this issue, I can't figure out of this is something easily built in or if it requires more python coding than I know.
I'm using resfinder (more specifically, starAMR) which provides a resfinder.tsv file with Gene, Start, End, and other columns.
I would like to adnotate a plasmid with prokka and build the adnotation from the gff file, which is clearly explained in your examples.
But I'd like to specifically use resfinder.tsv to adnotate AMR genes, and highlight the presence of these genes (perhaps by writting gene names in red).
The problem is that some genes would be present in both prokka.gff, as well as resfinder.tsv and their predicted names might be different. In my current case, prokka.gff adnotates a genes as "ampC" and resfinder.tsv identifies it as "CMY-2" (this is more specific, and this is what I'd want). I checked, the Start, End and Lenght are all the same.
My current understanding of python and mathlibplot (coming from a functional understanding of R and ggplot2) would lead me to try to make a combined dataframe (I hope this is not specific to R language) , substituting and appending the much larger prokka database with the resfinder hits based on Start and End match and perhaps add a custom column that would indicate AMR. Then when plotting, add an if statement that check for the AMR column, and use something like `xtick.set_color(color)`.

A second highlight I would like to add is on the genome from the prokka.gbk file. Some AMR hits are also present in the genome level. In this high level overview, there would be far fewer things to adnotate (you don't want to plot each gene). But it would require some kind of automatic jitter-adnotation that would allow each label to be clearly seen and a line leading to the gene location. I'm attaching an example from an adnotation made with prokksee. I would imagine that you can build a custom dataset with the genes of interest, perhaps a classification column, and again take advantage of a way to use different colors to highlight the classification/function.
![jitter-plot](https://github.com/moshi4/pyCirclize/assets/60519483/38230997-6fe7-44d1-ae01-40fc9d8c43b8)

**Comment by moshi4** [comment]
1. **Plot prokka gff with resfinder result**
I think you can rename genes and add newly identified AMR genes to `prokka.gff` based on `resfinder.tsv`. Then plot the modified gff with pyCirclize and you should be able to do what you want. It is not particularly difficult, and there are other ways to do it, so I have no further advice. 

2. **Adjust the positions of neighboring labels**
I tried to implement this function before, but it was quite troublesome, so I left it unimplemented. I may implement it when I feel like it.
