### ISSUE TITLE
Custom color for genomic features

### ISSUE THREAD

**Issue by rdistefano** [moshi4/pyCirclize#64]
Hi. First of all, thank you for this fantastic package!

I use pyCirclize to generate a circos reporting variants across a prokaryotic genome. In particular, I leverage the `genomic_features` function to include a list of SeqFeatures, one for each variant, to include them within a track. Now, it is unclear to me how to override the color specification and assign a specific color to each SeqFeature (I have embedded the hex color in each SeqFeature as `qualifiers={"facecolor": "#fd8d00"}`).

I appreciate your help!

**Comment by moshi4** [comment]
Hi @rdistefano,

Discussion in #41 and [this example](https://moshi4.github.io/pyCirclize/plot_api_example/#3-15-2-gff-file) may helpful for you.

**Comment by rdistefano** [comment]
Thank you for the quick response. That's the answer I was looking for!
