### ISSUE TITLE
Support for comparative genomics visualization

### ISSUE THREAD

**Issue by Dx-wmc** [moshi4/pyCirclize#73]
Hi, I've been using pycircliz for visualizing single genome circular plots and find it very useful. However, I'm wondering if there are plans to implement features for comparing multiple genomes in a single plot? Just like the function implemented by mummer2circos.

**Comment by moshi4** [comment]
pyCirclize is being developed as a general-purpose circular visualization library. There are no plans to implement specialty-focused features such as comparative genomics in pyCirclize.
