### ISSUE TITLE
to_link() to many links

### ISSUE THREAD

**Issue by hschult** [moshi4/pyCirclize#75]
Hi and thank you for this awesome plotting library!

Unfortunately, I may have found a small bug. Running this code I get (with pycirclize `1.6.0` and `1.7.0`):

```
import pandas as pd
import pycirclize

table = pd.DataFrame({"from": ["a"], "to": ["aa"], "value": [1]})

pycirclize.parser.Matrix.parse_fromto_table(table).to_links()
```
-> `[(('aa', 0.0, 1.0), ('a', 1.0, 0.0)), (('a', 1.0, 2.0), ('aa', 2.0, 1.0))]` but I expected `[(('a', 0.0, 1.0), ('aa', 1.0, 0.0))]`.
Interestingly, when I rename "aa" to "a1" this works as expected.

**Comment by moshi4** [comment]
Hi @hschult, 

Thank you for report this bug. Fixed in [v1.7.1](https://github.com/moshi4/pyCirclize/releases/tag/v1.7.1) release.
